# Generated by Django 3.2.5 on 2022-10-10 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='docname',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
