# Generated by Django 3.2.5 on 2022-10-10 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_document_docname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='docname',
            new_name='name',
        ),
    ]
