# Generated by Django 3.2.16 on 2022-11-21 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_report_is_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='bbq_filter',
        ),
        migrations.RemoveField(
            model_name='report',
            name='document',
        ),
        migrations.RemoveField(
            model_name='report',
            name='pet_filter',
        ),
        migrations.RemoveField(
            model_name='report',
            name='rental_filter',
        ),
        migrations.RemoveField(
            model_name='report',
            name='smoking_filter',
        ),
    ]
