# Generated by Django 3.2.16 on 2022-11-21 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_auto_20221121_0655'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='can_generate',
            field=models.BooleanField(default=False),
        ),
    ]
