# Generated by Django 3.2.16 on 2022-12-16 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_remove_report_predictions'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='already_generated',
            field=models.BooleanField(default=False),
        ),
    ]
