# Generated by Django 4.1.3 on 2022-12-30 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_report_already_generated'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='already_scanned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(default='Created', max_length=255),
        ),
    ]
