# Generated by Django 3.2.16 on 2022-12-30 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_report_already_scanned_report_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='already_scanned',
        ),
    ]
