# Generated by Django 3.2.16 on 2022-11-03 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='doc_page_length',
            field=models.IntegerField(default=0),
        ),
    ]
